#- name: add the webservers to the load balancer
#  local_action: ec2_elb
#  args:
#    instance_id: "{{ item.id }}"
#    ec2_elbs: anil-load-balancer
#    state: present
#    region: us-west-1
#  with_items: ec2.tagged_instances

- name: Instance Register
  local_action:
      module: ec2_elb
      instance_id: "{{ ansible_ec2_instance_id }}"
      ec2_elbs: "{{ item }}"
      state: present
  with_items: "{{ ec2_elbs }}"
