- name: Create the ELB only listening over port 80
  local_action:
     module: ec2_elb_lb
     ec2_elb_lb:
     name: anil-load-balancer
     state: present
     region: us-west-1
     zones:
       - us-west-1a
       - us-west-1b
     listeners:
         - protocol: http
           load_balancer_port: 80
           instance_port: 80
     register: ec2_elbs
     tags:
        - create_load_balancer
- name: Instance Register
  local_action:
      module: ec2_elb
      instance_id: "{{ ansible_ec2_instance_id }}"
      ec2_elbs: "{{ item }}"
      state: present
  with_items: "{{ ec2_elbs }}"

