- name: Create an EC2 instance
  local_action:
        module: ec2
        key_name: "{{ pem_key }}"
        region: "{{ region }}"
        group_id: "{{ demo_firewall.group_id }}"
        instance_type: "{{ instance_type }}"
        image: "{{ ami }}"
        wait: yes
        instance_tags:
            env: "{{ env }}"
        count: 1
        vpc_subnet_id: subnet-f98a919e
        assign_public_ip: yes
  register: ec2

- name: Add the newly created EC2 instance(s) to the local host group (located inside the directory)
  local_action: lineinfile
                  dest="./hosts"
                  regexp={{ item.public_ip }}
                  insertafter="[launched]" line="{{ item.public_ip }} ansible_ssh_private_key_file=~/.ssh/{{ pem_key }}.pem"
  with_items: ec2.instances
- name: Wait for SSH to come up
  wait_for: host={{ item.public_ip }} port=22 delay=60 timeout=320 state=started
  with_items: ec2.instances

#- name: Wait for SSH to come up
#  delegate_to: "{{ item.public_dns_name }}"
#  wait_for_connection:
#        delay: 60
#        timeout: 320
#  with_items: "{{ ec2.instances }}"
#- name: Add new instance to host group
#  add_host:
#     hostname: "{{ item.public_ip }}"
#     groups: local
#  with_items: "{{ ec2.instances }}"

#- name: wait for the servers to appear on the network
#  wait_for: host={{ item.public_dns_name }} port=22 delay=10 timeout=180 state=started
#  with_items: ec2.tagged_instances
#
#- name: add server ip addresses to hosts group
#  add_host: hostname={{ item.public_ip }} groupname=launched
